#ifndef RHYOLITEINPUT_GLOBAL_H
#define RHYOLITEINPUT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RHYOLITEINPUT_LIBRARY)
#define RHYOLITEINPUT_EXPORT Q_DECL_EXPORT
#else
#define RHYOLITEINPUT_EXPORT Q_DECL_IMPORT
#endif

#endif // RHYOLITEINPUT_GLOBAL_H
